name: Check

on:
  pull_request:
    paths-ignore:
    - '.github/**'
  workflow_dispatch:
  push:
    branches:
    - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: cachix/install-nix-action@v23
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

    - run: nix profile install .#elixir

    - run: |
        mix local.hex --force
        mix deps.get
        mix deps.compile

    - run: mix format

    - run: mix dialyzer

    # - run: mix credo

    - run: mix test

    # Check the flake outputs
    # - run: nix flake check
